name: Tests & Coverage

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable

      - name: Install souls-cli
        run: cargo install souls-cli

      - name: Run CLI(Souls -> Test)
        run: s test
      
      - name: Publish on crates test
        run: cargo publish --dry-run

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      
      - name: Run coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ./lcov.info